import ReactMarkdown from "react-markdown";
import rehypeKatex from "rehype-katex";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";

function normalizeMathDelimiters(raw) {
  if (!raw) return "";

  let text = raw;

  // Normalize escaped line break markers often generated by LLM: " \ " -> newline.
  text = text.replace(/\s\\\s+/g, "\n");

  // Đơn giản hóa \text{...} -> ... để tránh lỗi KaTeX với text tiếng Việt dài.
  text = text.replace(/\\text\{([^}]*)\}/g, "$1");

  // Force every $$...$$ chunk to standalone display block.
  text = text.replace(/\$\$([\s\S]*?)\$\$/g, (_match, latex) => {
    const candidate = String(latex || "").trim();
    if (!candidate) return _match;
    return `\n$$\n${candidate}\n$$\n`;
  });

  // Remove stray backslash tokens immediately after a math block: "$$...$$ \"
  text = text.replace(/(\$\$)\s*\\+(?=\s|$)/g, "$1");

  // Convert common non-standard AI output: [ \frac{...} ] -> $$ \frac{...} $$
  text = text.replace(/\[\s*(\\[\s\S]*?)\s*\]/g, (_match, latex) => {
    const candidate = String(latex || "").trim();
    if (!candidate) return _match;
    return `\n$$\n${candidate}\n$$\n`;
  });

  // Convert escaped block delimiters to $$ blocks for consistent rendering.
  text = text.replace(/\\\[\s*([\s\S]*?)\s*\\\]/g, (_match, latex) => {
    const candidate = String(latex || "").trim();
    if (!candidate) return _match;
    return `\n$$\n${candidate}\n$$\n`;
  });

  // Convert plain LaTeX-looking lines (without delimiters) into block math.
  // Example: "\text{...} = \frac{...} \" -> "$$ ... $$"
  const mathLike = /\\(frac|text|times|cdot|sqrt|left|right|sum|int|leq|geq|mathrm|operatorname)\b/;
  const lines = text.split(/\r?\n/);
  text = lines
    .map((line) => {
      const original = line;
      const trimmed = original.trim();
      if (!trimmed) return original;
      if (trimmed.includes("$$")) return original;
      if (!mathLike.test(trimmed)) return original;

      // AI sometimes uses trailing "\" as visual line break.
      const cleaned = trimmed.replace(/\\+\s*$/, "").trim();
      if (!cleaned) return original;
      return `$$ ${cleaned} $$`;
    })
    .join("\n");

  // Normalize excessive blank lines after conversions.
  text = text.replace(/\n{3,}/g, "\n\n");
  return text.trim();
}

export default function MessageBubble({ message }) {
  const isUser = message.role === "user";
  const normalizedContent = normalizeMathDelimiters(message.content || "");

  return (
    <article className={`flex ${isUser ? "justify-end" : "justify-start"}`}>
      <div
        className={`max-w-[90%] rounded-2xl px-5 py-4 text-base shadow-sm md:max-w-[82%] ${
          isUser
            ? "bg-teal-600 text-white"
            : "border border-teal-100 bg-white text-slate-700"
        }`}
      >
        <p
          className={`mb-2 text-xs font-semibold tracking-wide uppercase ${
            isUser ? "text-teal-50" : "text-teal-600"
          }`}
        >
          {isUser ? "Bạn" : "KidneyCare AI"}
        </p>
        <div className="space-y-3 leading-7 markdown-content">
          <ReactMarkdown
            remarkPlugins={[remarkGfm, remarkMath]}
            rehypePlugins={[rehypeKatex]}
            components={{
              p: (props) => <p className="mb-2 leading-7" {...props} />,
              h1: (props) => <h1 className="mb-2 text-2xl font-semibold" {...props} />,
              h2: (props) => <h2 className="mb-2 text-xl font-semibold" {...props} />,
              h3: (props) => <h3 className="mb-1 text-lg font-semibold" {...props} />,
              ul: (props) => <ul className="mb-2 list-disc space-y-1 pl-6" {...props} />,
              ol: (props) => <ol className="mb-2 list-decimal space-y-1 pl-6" {...props} />,
              li: (props) => <li className="leading-7" {...props} />,
              table: (props) => (
                <div className="my-3 overflow-x-auto rounded-xl border border-teal-100">
                  <table className="min-w-full border-collapse text-sm" {...props} />
                </div>
              ),
              thead: (props) => <thead className="bg-teal-50 text-slate-800" {...props} />,
              tbody: (props) => <tbody className="bg-white" {...props} />,
              tr: (props) => <tr className="border-b border-teal-100 last:border-b-0" {...props} />,
              th: (props) => (
                <th
                  className="px-3 py-2 text-left text-xs font-semibold tracking-wide text-teal-700 uppercase"
                  {...props}
                />
              ),
              td: (props) => <td className="px-3 py-2 align-top leading-6 text-slate-700" {...props} />,
              hr: (props) => <hr className="my-3 border-white/30" {...props} />,
              code: ({ inline, className, children, ...props }) =>
                inline ? (
                  <code className="rounded bg-black/10 px-1 py-0.5 text-[0.95em]" {...props}>
                    {children}
                  </code>
                ) : (
                  <code className={`block overflow-x-auto rounded-lg bg-black/10 p-3 ${className || ""}`} {...props}>
                    {children}
                  </code>
                ),
            }}
          >
            {normalizedContent}
          </ReactMarkdown>
        </div>
        {message.imagePreview && (
          <img
            src={message.imagePreview}
            alt="Uploaded medical record"
            className="mt-3 h-28 w-28 rounded-lg object-cover ring-2 ring-white/30"
          />
        )}
      </div>
    </article>
  );
}
